set enc=utf-8
set fencs=utf-8,ucs-bom,shift-jis,gb108830,gbk,gb2312,cp936
set langmenu=zh_CN.UTF-8
set helplang=cn
filetype on
syntax enable
set backspace=2
set nu
set history=100
colo torte
set guifont=Monospace\ Bold\ 11
set background=dark
set mouse=a
"auto reload when file is changed
set autoread
"not back up
set nobackup
set ruler
set cursorline
set cursorcolumn
set magic
"disable tools and menubar
set guioptions-=T
set guioptions-=m
set ai
set ci
set smartindent
"tab length
set tabstop=4
set shiftwidth=4
set noswapfile
set ignorecase
set hlsearch
set incsearch
set laststatus=2
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey40
hi Cursorcolumn term=bold cterm=bold guibg=Grey40
let g:netrw_liststyle=3
nnoremap <C-Tab> :tabprevious<CR>
nnoremap <Tab> :tabnext<CR>

"vim can use file manager with itsself
"use :E to open file manager in current buffer
"user :Te to open file manager in a new tab buffer
"in file manage,use o/v/t to open file in horizontal/vertical/tab 

"move in insert mode
inoremap <C-h> <left>
inoremap <C-j> <C-o>gj
inoremap <C-k> <C-o>gk
inoremap <C-l> <Right>
inoremap <M-h> <C-o>b
inoremap <M-l> <C-o>w
inoremap <C-a> <Home>
inoremap <C-e> <End>

"nerd tree
map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>

let mapleader=","

vmap <Leader>al <Plug>(EasyAlign)
nmap <Leader>al <Plug>(EasyAlign)

au InsertLeave * hi Cursor guibg=red
au InsertEnter * hi Cursor guibg=green
"auto reload vimrc
autocmd! bufwritepost $HOME/.vimrc source %
